### ISSUE TITLE
using --from-file on a KeyValueList type can't handle URLs

### ISSUE THREAD

**Issue by talkammer** [redhat-openstack/infrared#284]
When defining a KeyValueList type which includes the delimiter character ":" and generating an answer file from it, the INI file which is created cannot be parsed later on with the "--from-file" flag.
Example:

infrared example --generate-answers-file example.ini

example.ini:
[example]
foo-bar = foo:http://example.com,bar:https://example.com

infrared example --from-file example.ini
<snip>
ERROR   'foo:http://example.com,bar:https://example.com' is a wrong format for 'KeyValueList' argument type. Please enter values in the following format: NodeA:1,NodeB:2...

trying to add "" or '' around the urls results in the same error.

**Comment by talkammer** [comment]
@obaranov @ovorobio @aopincar @atalmor Just wondering if someone got a chance to look at this?
(I can work on this this weekend if it's not a trivial fix)

**Comment by ovorobio** [comment]
Hello Tal,

Please check this patch, it should fix the issue: https://review.gerrithub.io/377034

**Comment by talkammer** [comment]
@ovorobio works like a charm :) . thanks!
