### ISSUE TITLE
Install from CDN

### ISSUE THREAD

**Issue by coolpalani** [redhat-openstack/infrared#285]
I have RedHat subscriptions, but couldn't find this file for fixing it

rhos_release_rpm: "https://url.corp.redhat.com/rhos-release-latest-rpm"
rhos_release_rpm: "http://{{ mirror_fqdn }}/rhos-release/repos/rhos-release/rhos-release-latest.noarch.rpm"

**Comment by yfried** [comment]
Hi @coolpalani,
I apologize for the inconvenience.

rhos-release is an internal rehdat tool for installing pre-release version's of OSP.
We are currently in the process of adding CDN support. I will try to update this ticket as soon as we have a WIP patch.

In the meantime, you could try installing RDO.

Regards
Yair

**Comment by coolpalani** [comment]
Thank you very much for your response.
I think achieving HA with RDO packstack isn't straight forward.
so that's what I am looking your repo to overcome complicity.

if you have valid steps for achieve RHOSP with HA through packstack, kindly share with me. I would appreciate your help.

**Comment by yfried** [comment]
What version of Openstack are you using? Are you looking for VMs, or
Bare-metal deployment?

As far as I know, HA is not supported in any version of packstack.

Regards
Yair

On May 4, 2017 18:50, "coolpalani" <notifications@github.com> wrote:

Thank you very much for your response.
I think achieving HA with RDO packstack isn't straight forward.
so that's what I am looking your repo to overcome complicity.

if you have valid steps for achieve RHOSP with HA through packstack, kindly
share with me. I would appreciate your help.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/redhat-openstack/infrared/issues/285#issuecomment-299227363>,
or mute the thread

**Comment by coolpalani** [comment]
I am trying to install RHOSP-10 in Virtual machine

**Comment by rhosqeauto** [comment]
OK. In that case, I hope to have a first draft by Monday. I will count on
you to help verify it.

Regards
Yair

**Comment by coolpalani** [comment]
Thank you very much.
Please try to provide complete installations repo.
Undercloud+Overcloud(Controller,Compute,Ceph)

**Comment by yfried** [comment]
Hi,
I've submitted a very first draft:
https://review.gerrithub.io/#/c/359903/

It should allow undercloud installation. I haven't fully checked but I believe overcloud images should work as well.
I will start working on registering the overcloud nodes next, but AFAIK, you should be able to deploy the overcloud as is without that feature and simply avoid updating the overcloud.

To use the new feature, create a file with your redhat subscription_manager details (see [smaple](https://review.gerrithub.io/#/c/359903/1/plugins/tripleo-undercloud/vars/cdn/cnd_creds.yml.sample) file) and pass it as follow:
```
infrared tripleo-undercloud [...] --version 10 --cdn /path/to/file.yml
```
All options [documented](http://docs.ansible.com/ansible/redhat_subscription_module.html) are supported.

**Comment by coolpalani** [comment]
Hi,

Can I specify the pool ID in the below playbook instead of autosubscribe options
##########
server_hostname: example.redhat.com
username: user
password: HIDDEN_PASS
autosubscribe: yes
server_insecure: yes
##########

**Comment by yfried** [comment]
Hi,
According to http://docs.ansible.com/ansible/redhat_subscription_module.html
``pool: `` supports names and regex. I'm not sure if ID will work. Please try, and let me know

**Comment by coolpalani** [comment]
Hello Yfried,

Please let me know how do i register overcloud node with RedHat Subscriptions.

Is following command work?

infrared tripleo-overcloud [...] --version 10 --cdn plugins/tripleo-undercloud/vars/cdn/cnd_creds.yml

In fact I am following this documents.
https://iranzo.github.io/blog/2017/02/23/infrared-for-deploying-openstack/

After i ran above command should i run this one also?

time infrared tripleo-overcloud --deployment-files virt --version $VERSION --introspect yes --tagging yes --post yes

Kindly let me know the sequence.
Thanks in advance.

**Comment by yfried** [comment]
Hi, we will add cdn for the overcloud part shortly. However, you should still be able to deploy using the second command you mentioned, with the only downside being that the overcloud nodes aren't registered.

Please let me know if you experience any issues. If not, we will add the registration feature by next week.

You should still be able to register them manually post-install.

**Comment by coolpalani** [comment]
Hello Yfried

One more concern regarding cdn registrations in Undercloud node. 
When we use RHEL subscriptions, you aren't covering this following task in playbook.

##########
sudo yum install rhosp-director-images rhosp-director-images-ipa
$mkdir ~/images
$ cd ~/images
$ for i in /usr/share/rhosp-director-images/overcloud-full-latest-10.0.tar /usr/share/rhosp-director-images/ironic-python-agent-latest-10.0.tar; do tar -xvf $i; done
$ openstack overcloud image upload --image-path /home/stack/images/
$ openstack image list
##########

I am using following command for undercloud installations.

time infrared tripleo-undercloud --version 10 --cdn plugins/tripleo-undercloud/vars/cdn/cdn_creds.yml

Am i anything missing for --images-task which you're not covering specifically for cdn kind of registrations

http://infrared.readthedocs.io/en/latest/tripleo-undercloud.html

**Comment by yfried** [comment]
Hi,
I believe what you are looking for is 
```
infrared tripleo-undercloud --images-task rpm
```
As part of the install command (``--version 10 --cdn foo ...``), or as a followup step.
Documented in http://infrared.readthedocs.io/en/latest/tripleo-undercloud.html#overcloud-images

If you are using RDO, you will have to use ``build`` or ``import`` as detailed.

Also, note that you no longer have to inject your creds file ``plugins/tripleo-undercloud/vars``. Any path should work.

**Comment by coolpalani** [comment]
Hello Yfried,

Have you added cdn part for overcloud nodes where registering with RHEL subscriptions and fetching packages from rhel repo for complete overcloud deployment

**Comment by yfried** [comment]
Not yet, sorry.
We hope to do that in the next Sprint (starting tomorrow), but feel free to file a new issue on that.
I understand why this is needed and as I've said, we will add it shortly, but am I right to assume installation can work even with un-registered overcloud nodes?

**Comment by coolpalani** [comment]
Hello Yfried,

During overcloud node installations, I'm getting the following error.
It's trying to source overcloudrc file which isn't available in undercloud node.

TASK [find a server with the nova control plane service running] ************************************************************************
                     [[ previous task time: 0:00:05.319752 = 5.32s / 711.97s ]]
fatal: [undercloud-0]: FAILED! => {"changed": true, "cmd": "source ~/overcloudrc\n nova service-list | grep nova-scheduler | awk '{print $6}' | head -1", "delta": "0:00:00.004829", "end": "2017-06-05 05:10:46.959299", "failed": true, "rc": 1, "start": "2017-06-05 05:10:46.954470", "stderr": "/bin/sh: /home/stack/overcloudrc: No such file or directory", "stderr_lines": ["/bin/sh: /home/stack/overcloudrc: No such file or directory"], "stdout": "", "stdout_lines": []}

How do i sort out this problem?

I am trying to install rhosp version 10
