### ISSUE TITLE
Horizon UI not reachable

### ISSUE THREAD

**Issue by coolpalani** [redhat-openstack/infrared#289]
Dear Yfried,

Please provide steps for accessing horizon UI from web browser after overcloud deployment completed.
Thanks in advance.

**Comment by yfried** [comment]
Hi,
Here are the manual steps, I will add them to the playbooks shortly:

1. Get the overcloud floating IP from undercloud:/home/stack/overcloudrc
```bash
[stack@undercloud-0 ~]$ cat overcloudrc
# Clear any old environment that may conflict.
for key in $( set | awk '{FS="="}  /^OS_/ {print $1}' ); do unset $key ; done
export OS_NO_CACHE=True
export OS_CLOUDNAME=overcloud
export OS_AUTH_URL=http://10.0.0.109:5000/v2.0
export NOVA_VERSION=1.1
export COMPUTE_API_VERSION=1.1
export OS_USERNAME=admin
export OS_PASSWORD=FOO
export no_proxy=,10.0.0.109,192.168.24.7
export OS_PROJECT_NAME=admin
export PYTHONWARNINGS="ignore:Certificate has no, ignore:A true SSLContext object is not available"
```
2. Create a forward rule in hypervisor's iptables, that will send all incoming HTTP traffic to the overcloud's entrypoint

```
iptables -t nat -A PREROUTING -d 10.35.64.55/32 -p tcp -m tcp --dport 8080 -j DNAT --to-destination 10.0.0.109:80
```

3. Access your hypervisor via browser in port 8080: `http://10.35.64.55:8080`

**Comment by yfried** [comment]
@coolpalani  please see update above

**Comment by coolpalani** [comment]
Hi Yfried,

I am looking into this and will update you shortly.
