### ISSUE TITLE
Enabled LBaaS 

### ISSUE THREAD

**Issue by coolpalani** [redhat-openstack/infrared#290]
Dear Yfried,

How do I enable LBaaS,FWaaS in OverCloud node deployment. So that It would be available in OpenStack Horizon.

**Comment by yfried** [comment]
``infrared tripleo-overcloud --post yes --network-lbaas yes`` will enable LBaaS and since it's post-install you should be able to run it on an existing setup.
I'll have to check re FWaaS

**Comment by coolpalani** [comment]
Would it be okay this?

infrared tripleo-overcloud --deployment-files virt --version 10 --introspect no --taggin no --deploy yes --post yes --network-lbaas yes

**Comment by yfried** [comment]
If you have a working overcloud, you should set deploy to NO

Regards
Yair

**Comment by coolpalani** [comment]
Hello Yfried,

I used following playbook command in fresh installations machine, but lbaas isn't installed in overcloud node.

time infrared tripleo-overcloud --version=10 --deployment-files=virt --introspect=yes --tagging=yes  --deploy=yes --post=yes --network-lbaas yes

**Comment by yfried** [comment]
Hi @coolpalani 
Sorry for the long delay. I had to check around to make sure.
So following [your previous comment](https://github.com/redhat-openstack/infrared/issues/290#issuecomment-306789773) LBaaS should be configured on your overcloud and CLI commands should work. I've verified this on my own environment.

LBaaS dashboard, however, isn't configured by default.

If you've registered your overcloud to CDN properly, as we discussed in issue #288, you should be able to follow [this guide ](https://ask.openstack.org/en/question/96477/how-to-install-lbaas-v-20-dashboard-panels-in-horizon-packstack-installation/) replacing `git clone... setup.py ...` with `yum install openstack-neutron-lbaas-ui -y`

It worked for me, and I'm attaching a screen capture so you know what to look for

![screenshot from 2017-06-21 14-41-31](https://user-images.githubusercontent.com/5310525/27382449-c934270c-568f-11e7-9b8a-e2d36291527a.png)

Note that this is using the dashboard forwarding discussed added in #289.

**Comment by coolpalani** [comment]
Hello Yfried,

I am deploying RedHat OpenStack platform 11.
Once completed will post you the status whether LBaas has installed or not.

is there any options for upgrade openstack versions from 10 to 11 as directly without rebuild environment?
This is for my future deployment reference questions. It would be helpful.

**Comment by rhosqeauto** [comment]
Upgrade possible, though we haven't tested it using CDN yet.
However, it's a very lengthy process, approximately 30min per node, so I
think redeployment is a quicker (50 min to a working environment) option.

Regards
Yair

**Comment by coolpalani** [comment]
Hello Yfried,

I have successfully deployed RedHat OpenStack Platform 11.
For enabling LBaas, I installed openstack-neutron-lbaas-ui-2.0.0-3.el7ost.noarch.rpm in each controller node and change the enable_lb option to True in the /etc/openstack-dashboard/local_settings file.

Once I restarting the httpd.service, it appears in dashboard now.

Thank you very much!!!
