### ISSUE TITLE
Performance is poor in Virtual Environment

### ISSUE THREAD

**Issue by coolpalani** [redhat-openstack/infrared#291]
Hello Yfried,

We've 128GB RAM blade server with 600GB local Hard Disk. I have installed RHEL 7.3 with KVM and Desktop version.
I tried to run playbook but it gets failed.
Then I created one virtual machine in same blade server from KVM then ran this playbook. 
Everything went as good but performance is really poor in Virtual.
is there any possibility for directly run this playbook in RHEL 7.3 where I installed OS on blade server instead of work from kvm?

**Comment by aopincar** [comment]
Hi coolpalani,

Thanks for you comment! :-)
Not sure I understood what exactly do you need.
The defaults amount of resources for each node type have been written for older version of OpenStack. As of OS >= 10, VMs are much more greedy about resources. It's possible do define the amount of resources for each node type with IR's 'virsh' plugin.
In the example below, we set the number of CPU to 8 and number of RAM to 32GB for the controller nodes.

For example:
`infrared virsh --topology-nodes undercloud:1,controller:3,compute:1 .... -e override.controller.cpu=8 -e override.controller.memory=32768`

Let me know if it helps you or not.

Thanks,
Ariel

**Comment by coolpalani** [comment]
Hello Ariel,

Please click on this picture to understand my performance issue
https://i.imgur.com/g33OHAj.png

Since everything working in nested kvm, that's what performance is really lagging.
if I directly able to install in Baremetal node, then i won't face such an issue

**Comment by coolpalani** [comment]
Hello Ariel,

I am getting the following error message.

failed: [hypervisor] (item={'key': u'net3', 'value': {u'name': u'external', u'floating_ip': {u'start': u'10.0.0.101', u'end': u'10.0.0.150'}, u'external_connectivity': True, u'netmask': u'255.255.255.0', u'ipv6': {u'dhcp': {u'range': {u'start': u'2620:52:0:13b8::fe:1', u'end': u'2620:52:0:13b8::fe:ff'}}, u'prefix': u'64', u'ip_address': u'2620:52:0:13b8::fe'}, u'forward': u'nat', u'dhcp': {u'range': {u'start': u'10.0.0.2', u'end': u'10.0.0.100'}, u'subnet_cidr': u'10.0.0.0/24', u'subnet_gateway': u'10.0.0.1'}, u'ip_address': u'10.0.0.1'}}) => {
    "failed": true,
    "invocation": {
        "module_args": {
            "autostart": true,
            "command": null,
            "name": "external",
            "state": "active",
            "uri": "qemu:///system",
            "xml": null
        }
    },
    "item": {
        "key": "net3",
        "value": {
            "dhcp": {
                "range": {
                    "end": "10.0.0.100",
                    "start": "10.0.0.2"
                },
                "subnet_cidr": "10.0.0.0/24",
                "subnet_gateway": "10.0.0.1"
            },
            "external_connectivity": true,
            "floating_ip": {
                "end": "10.0.0.150",
                "start": "10.0.0.101"
            },
            "forward": "nat",
            "ip_address": "10.0.0.1",
            "ipv6": {
                "dhcp": {
                    "range": {
                        "end": "2620:52:0:13b8::fe:ff",
                        "start": "2620:52:0:13b8::fe:1"
                    }
                },
                "ip_address": "2620:52:0:13b8::fe",
                "prefix": "64"
            },
            "name": "external",
            "netmask": "255.255.255.0"
        }
    },
    "msg": "Failed to add IP address 2620:52:0:13b8::fe/64 to external"
}

**Comment by coolpalani** [comment]
Yfried,

Your attention is very much appreciated.

**Comment by coolpalani** [comment]
Thanks to everyone.
I found the problem and able to run this playbook directly on baremetal host.
I believe performance should be improve now.
