### ISSUE TITLE
RFE: Provide a way to use scheduler hints

### ISSUE THREAD

**Issue by smalleni** [redhat-openstack/infrared#293]
For large scale deployments, the OpenStack performance and scale team is recommending to deploy using scheduler hints(https://docs.openstack.org/developer/tripleo-docs/advanced_deployment/node_placement.html). Although the scheduler hints can be passed an extra yaml file during deployment time, we need the nodes to be tagged with  the equivalent of
```
ironic node-update <id> replace properties/capabilities='node:controller-0,boot_option:local'
```
Would it be possible to device a way like it is being done with tagging flavors currently, to tags each node with a per node capability.

This is very much needed for large scale baremetal deployments.

**Comment by yfried** [comment]
Do you mean, instead of tagging the node with "controller" label, to tag it with "controller-0", or did I completely miss you point?

**Comment by smalleni** [comment]
Yup tag it as in the above command, so that the nova scheduler always picks that node as controller-0.

**Comment by smalleni** [comment]
@yfried thoughts?

**Comment by obaranov** [comment]
@smalleni, we finally implemented that feature. You can take a look on the documentation here: http://infrared.readthedocs.io/en/latest/control_placement.html
