### ISSUE TITLE
Launching Instance Issue

### ISSUE THREAD

**Issue by coolpalani** [redhat-openstack/infrared#294]
Hello,

I am trying to launch instance from horizon.
Upon completion of playbook execution, public network has created as defined in the template. I should want create a private network also for launch an instance.

Can you provide exact private network details that I need to create ?

**Comment by yfried** [comment]
Hi @coolpalani,
The public network is required for external connectivity, and for testing, and requires knowledge available only to the cloud deployer/admin, this is why Infrared creates it. However, creating private tenant/project resources is out of scope for the overcloud deployment plugin.

Given openstack tenant-isolation you are free to create your networks however you like, and connect any/all of them to the public network created by Infrared.
Use [dashboard](https://docs.openstack.org/user-guide/dashboard-create-networks.html) or [CLI](https://docs.openstack.org/user-guide/cli-create-and-manage-networks.html) to do it manually, or write your own Ansible playbook to automate that

Regards
Yair
