### ISSUE TITLE
ansible DEPRECATON WARNINGS

### ISSUE THREAD

**Issue by yazug** [redhat-openstack/infrared#301]
[DEPRECATION WARNING]: 'include' for playbook includes. You should use 'import_playbook' instead. This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

This should get on the radar for getting fixed

**Comment by obaranov** [comment]
This one has been fixed by https://review.gerrithub.io/#/c/redhat-openstack/infrared/+/389741/
