### ISSUE TITLE
Stable points to https://url.corp.redhat.com/rhel-guest-image-7-4-210-x86-64-qcow2

### ISSUE THREAD

**Issue by iranzo** [redhat-openstack/infrared#307]
https://url.corp.redhat.com/rhel-guest-image-7-4-210-x86-64-qcow2 seems not to exist anymore
minimum is now 220

**Comment by iranzo** [comment]
I've created new short url for 220:

https://url.corp.redhat.com/rhel-guest-image-7-4-220-x86-64-qcow2

**Comment by iranzo** [comment]
https://review.gerrithub.io/392793

**Comment by fhubik** [comment]
Fixed in master and stable (https://review.gerrithub.io/#/c/392800/).
