### ISSUE TITLE
RFE - provide a --format json option for workspace node-list

### ISSUE THREAD

**Issue by talkammer** [redhat-openstack/infrared#310]
infrared is a great tool for automation.
one of the things that will greatly help in building wrapper bash scripts is the ability to extract the IPs oft he machines we just provisioned.

Currently, we can get that info with: ir workspace node-list
however, that prints the output as a table to the stdout and while it is possible to use awk/sed/grep to extract the IPs, it would be extremely helpful to have a "format" flag (that defaults to table) that we can specify as: (example)
ir workspace node-list --format=json
and the output will be something like:
`{
  nodes: [
    {
        name: 'aio1',
        address: <IP ADDRESS>,
        groups: []
    }
  ]
}`

**Comment by aopincar** [comment]
Hi Tal,

A ticket (#1624) has been opened for this one.

Thanks,
Ariel

**Comment by aopincar** [comment]
A [patch](https://review.gerrithub.io/#/c/403015/) has been submitted.
(In the future, we'll redesign the code to support different formats for all outputs)

**Comment by obaranov** [comment]
Patch is merged to the master. Now node-list format can be controlled with -f flag. Closing that ticket.

**Comment by talkammer** [comment]
@aopincar @obaranov thank you!
