### ISSUE TITLE
[BUG] - ir workspace node-list has workspace related flags

### ISSUE THREAD

**Issue by talkammer** [redhat-openstack/infrared#311]
ir workspace node-list is implemented as subparser thus allowing the user to do something like:
`
ir workspace node-list --help
usage: ir workspace node-list [-h] [-n NAME] [-g GROUP]

optional arguments:
  -h, --help            show this help message and exit
  -n NAME, --name NAME  Workspace name
  -g GROUP, --group GROUP
`

Which prints confusing (non working) flags

**Comment by aopincar** [comment]
Hi Tal,

A ticket (#1625) has been opened for this one.

Thanks,
Ariel

**Comment by aopincar** [comment]
A [patch](https://review.gerrithub.io/403029) patch has been submitted.
Currently, the patch fixes only the functionality of the 'group' flag for the 'workspace node-list' command.
Fixes for other flags require changes in API, and will have to wait for a newer major version of InfraRed.

**Comment by obaranov** [comment]
I tested that on master and --group now works well now. I'm closing that issue now. @talkammer please reopen or create another issues if problem is still present. thanks!
