### ISSUE TITLE
infrared ssh alter stdout new lines characters when executing a command

### ISSUE THREAD

**Issue by FedericoRessi** [redhat-openstack/infrared#315]
To edit overcloudrc file with the purpose of connecting to overcloud API from remote machine I executed below command:
```bash
$ infrared ssh undercloud-0 "cat overcloudrc" > overcloudrc
```

Produced file has corrupted new lines and therefore is not accepted by bash source command:
```bash
$ source overcloudrc 
bash: overcloudrc: line 25: syntax error: unexpected end of file
```

To workaround the problem I had to cleanup new lines using dos2unix command
```bash
$ dos2unix overcloudrc
$ source overcloudrc
```

**Comment by atalmor** [comment]
Hi,
as I didn't find any way to control the local file encoding via ssh/ssh_config, soI may suggest you to continue using dos2unix command before sourcing it

**Comment by FedericoRessi** [comment]
@atalmor The file encoding shouldn't matter. Data should be transferred byte by byte as a byte array and not a string without, any alteration or processing. Probably the problem here is converting bytes to string and back to bytes. What I saw is that somehow probably when sending the data there is a '\r' or some another extra byte that is added in the stream. You shouldn't look at ssh_config file as example. Any stdout or stderr of any command should be transferred without any alteration byte by byte. This is still a bug as this behavior doesn't conform with the behavior of any ssh client.

**Comment by FedericoRessi** [comment]
I made some investigation. The problem appear to be the -t parameter passed by infrared to ssh command. Removing it, then produced output is expected one.
