### ISSUE TITLE
The deployment fails in shade virtualenv core deps

### ISSUE THREAD

**Issue by Kosal-Raj** [redhat-openstack/infrared#318]
// I am facing the error for RHOSP 10

TASK [shade : shade virtualenv core deps] ***********************************************************************************************************************************
failed: [hypervisor] (item=setuptools==17.0) => {"changed": false, "failed": true, "item": "setuptools==17.0", "msg": "Failed to find required executable virtualenv in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin"}
failed: [hypervisor] (item=pip==9.0.1) => {"changed": false, "failed": true, "item": "pip==9.0.1", "msg": "Failed to find required executable virtualenv in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin"}

NO MORE HOSTS LEFT **********************************************************************************************************************************************************
	to retry, use: --limit @/root/.venv_infrared/infrared/plugins/tripleo-undercloud/main.retry

PLAY RECAP ******************************************************************************************************************************************************************
hypervisor                 : ok=11   changed=3    unreachable=0    failed=1   
localhost                  : ok=7    changed=4    unreachable=0    failed=0   
undercloud-0               : ok=30   changed=19   unreachable=0    failed=0   

ERROR   Playbook "/root/.venv_infrared/infrared/plugins/tripleo-undercloud/main.yml" failed!
(.venv_infrared)[root@dell-r430-13 infrared]#

**Comment by obaranov** [comment]
Hi @Kosal-Raj,

What OS you have on your hypervisor? Can you please also past the complete ansible log? I'm especially interested in the "install virtualenv pip module" task from the shade role. This tasks should install virtualenv module but form your log it seems that this package is missing.

**Comment by Kosal-Raj** [comment]
Hi @obaranov,

[root@dell-r430-13 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)
[root@dell-r430-13 ~]# 
[root@dell-r430-13 ~]# grep -iR "install virtualenv pip module" .venv_infrared/
.venv_infrared/lib/python2.7/site-packages/infrared/common/roles/shade/tasks/main.yml:- name: install virtualenv pip module
.venv_infrared/lib64/python2.7/site-packages/infrared/common/roles/shade/tasks/main.yml:- name: install virtualenv pip module
.venv_infrared/infrared/infrared/common/roles/shade/tasks/main.yml:- name: install virtualenv pip module
.venv_infrared/infrared/.library/infrared-common-libraries/roles/shade/tasks/main.yml:- name: install virtualenv pip module

I don't see the log is captured for it.

The console output for it is,

[root@dell-r430-13 ~]# grep -A15 "install virtualenv pip module" /tmp/steps.out
TASK [shade : install virtualenv pip module] ***********************************
ok: [hypervisor]

TASK [shade : cleanup shade venv if present] ***********************************
ok: [hypervisor]

TASK [shade : shade virtualenv core deps] **************************************
failed: [hypervisor] (item=setuptools==17.0) => {"changed": false, "failed": true, "item": "setuptools==17.0", "msg": "Failed to find required executable virtualenv in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin"}
failed: [hypervisor] (item=pip==9.0.1) => {"changed": false, "failed": true, "item": "pip==9.0.1", "msg": "Failed to find required executable virtualenv in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/root/.venv_infrared/infrared/plugins/tripleo-undercloud/main.retry

PLAY RECAP *********************************************************************
hypervisor                 : ok=11   changed=3    unreachable=0    failed=1   
localhost                  : ok=7    changed=4    unreachable=0    failed=0   
[root@dell-r430-13 ~]#

**Comment by obaranov** [comment]
@Kosal-Raj, 
Hmm. According to the log you sent, virtualenv package was installed successfully.  So I don't understand why ansible cannot find vrtiualenv executable.

Try to do the following steps: 
1) Remove completely shade venv on the hypervisor->/var/tmp/venv_shade. Maybe that env is broken...
2) Make sure you have virtualenv pip package installed globally. Or install python-virtualenv package with yum. Run virtualenv command manually and make sure it works.

**Comment by Kosal-Raj** [comment]
@obaranov The issue is resolved.
