### ISSUE TITLE
Default TripleO undercloud password should not be "stack"

### ISSUE THREAD

**Issue by booxter** [redhat-openstack/infrared#321]
I've heard a story about a guy who installed TripleO with infrared and exposed it to external network, only to find later that his setup was hijacked and was mining Monero cryptocurrency.

This wouldn't happen if Infrared would enforce setting a password by default. I think this [1] shouldn't have a default.

[1] https://github.com/redhat-openstack/infrared/blob/c3163c12fb57f68bdc4673a5994fe8b00ca1ebf5/plugins/tripleo-undercloud/plugin.spec#L180

**Comment by obaranov** [comment]
@booxter, thank you for the report. I created an internal jira ticket to track this work. You can check RHOSINFRA-1744. Anyway I will keep you updated here as well.

**Comment by obaranov** [comment]
@booxter, we decided to not generate passwords or provide more complex password. In case you use default password you will see a warning at the end of the deployment. Also we updated documentation and --help output to warn user. See patch here: https://review.gerrithub.io/#/c/redhat-openstack/infrared/+/409293/
