### ISSUE TITLE
RFE: validate that virt host machine is NTP synced

### ISSUE THREAD

**Issue by jistr** [redhat-openstack/infrared#331]
It's not enough that we provide correct NtpServers to the overcloud Heat stack. If the setup is virtual, the VMs will get time from the hypervisor until they sync themselves via NTP. If the time is offset and there's an abrupt jump as the NTP sync takes effect, a wide variety of problems can appear. The only defense is to make sure that the virt host is NTP-synced too.

Infrared should at least validate that the virt host machine is NTP-synced, and refuse to run if it isn't.

**Comment by jistr** [comment]
Missing NTP sync can cause e.g. https://bugzilla.redhat.com/show_bug.cgi?id=1578849

**Comment by mwhahaha** [comment]
Please do not solve this in infrared as this is a deployment related problem which should be solved in tripleo since NTP/timezone is managed during the deployment.  This may mask actual failures if it's done in infrared
