### ISSUE TITLE
virtualbmc errors

### ISSUE THREAD

**Issue by tliron** [redhat-openstack/infrared#337]
There are two problems. First, is that virtualbmc cannot be installed from PyPI as is because InfraRed tries to install the latest version, and the latest version [(1.4.0 from August 9 2018)](https://pypi.org/project/virtualbmc/#history) conflicts with existing Python libraries in the undercloud.

This first problem can be fixed by patching [the vbmc role](https://github.com/redhat-openstack/infrared/blob/stable/infrared/common/roles/vbmc/tasks/install.yml), in the pip command, to install "virtualbmc==1.3.0" instead of plain "virtualbmc".

With that, the Python library can be installed. However, now there is a second problem:

> Unable to start service virtualbmc: Job for virtualbmc.service failed because the control process exited with error code. See "systemctl status virtualbmc.service" and "journalctl -xe" for details.

I suspect it might be related to [this issue](https://bugs.launchpad.net/tripleo/+bug/1790109). Meaning that perhaps it's necessary to upgrade to 1.4.0.

What can we do?

**Comment by tliron** [comment]
Related: the role mentioned above first tries to install `python-virtualbmc` from the "repo's" (that's a typo, by the way, should be "repos"). But in CentOS the package is called `python2-virtualbmc`. Perhaps both names should be attempted?

**Comment by tliron** [comment]
I see [this commit](https://review.gerrithub.io/c/redhat-openstack/infrared/+/428001/) as related., but it doesn't actually address the issues I raise here.

**Comment by rusichen** [comment]
Hi @tliron if issue resolved for you, please close it. Thanks!
