### ISSUE TITLE
http 404 on ceph-hammer undercloud repo since 15b09251c10f5

### ISSUE THREAD

**Issue by zzzeek** [redhat-openstack/infrared#338]
after the change to ceph repos in 15b09251c10f5dd218657573add474ffd7c4f2d7 I am getting this, as soon as it tries to use the undercloud repos, the commit right before this change there is no problem:

```
TASK [install deltarpm] ******************************************************************************************************************************************************
****
task path: /home/classic/dev/stretch_cluster/checkouts/infrared/plugins/tripleo-undercloud/setup_packages.yml:97
fatal: [s1undercloud-0]: FAILED! => {"changed": false, "msg": "Failure talking to yum: failure: repodata/repomd.xml from centos-ceph-hammer: [Errno 256] No more mirrors to tr
y.\nhttp://mirror.centos.org/centos/7/storage/x86_64/ceph-hammer/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found"}

```

my infrared command is:

    infrared tripleo-undercloud -vv --version stein -e rr_use_public_repos=true -e rr_release_name=master

**Comment by rusichen** [comment]
hi @zzzeek, thanks for created issue, i'll provide fix asap.

**Comment by rusichen** [comment]
@zzzeek I've submitted patch, please review it [1]

[1] https://review.gerrithub.io/#/c/redhat-openstack/infrared/+/430300/

**Comment by rusichen** [comment]
@zzzeek Patch with fix has been merged, please check that issue is resolved from your side.

Thanks!

**Comment by zzzeek** [comment]
hey there,  I haven't gotten to try it yet but it looks like the right idea, thanks!

**Comment by rusichen** [comment]
@zzzeek  hi, did it help you, if yes, please resolve issue. Thanks!

**Comment by zzzeek** [comment]
haven't gotten to test yet but I'll reopen if it fails again, thanks!

**Comment by zzzeek** [comment]
just tested, works great thanks!
