### ISSUE TITLE
Ironic commands have been deprecated, need to use "openstack baremetal" commands instead

### ISSUE THREAD

**Issue by bfournie** [redhat-openstack/infrared#377]
In OSP-16, the ironic commands have been fully deprecated and removed.  The corresponding "openstack baremetal" commands should be used instead.

For example, the "ironic node-list" command here:
https://github.com/redhat-openstack/infrared/blob/master/plugins/tripleo-overcloud/tasks/introspection_recovery.yml#L10

Should be replaced with:
"openstack baremetal node list"

**Comment by bfournie** [comment]
This has been fixed, closing.

**Comment by msalmanmasood** [comment]
how to reset provisioning state of a baremetal node from error to available using openstack client?
